name: Build Revanced Apps

on:
  workflow_dispatch:

jobs:
  build-youtube:
    name: Build YouTube
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: 3.11.2

      - name: Install Pip Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Build
        run: python main.py youtube

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: revanced-youtube
          path: |
            revanced-cache/output-youtube_signed.apk

  build-youtube-music:
    name: Build YouTube Music
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: 3.11.2

      - name: Install Pip Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Build
        run: python main.py youtube-music

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: revanced-youtube-music
          path: |
            revanced-cache/output-youtube-music_signed.apk
