name: Lint Project

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"

      - name: Install Dependencies
        run: |
          pypy -m pip3 install --upgrade pip
          pypy -m pip3 install -r requirements.txt

      - name: Run Lint
        run: pypy -m ruff .
