name: Lint Project

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: 3.11.2

      - name: Install Dependencies
        run: poetry install

      - name: Run Lint
        run: ruff check .
